export const activitiesData = [
  "Horse riding",
  "High-trekking",
  "Camping",
  "Sleeping at yurt",
  "Off-road",
  "Expedition",
  "Self-driving",
  "Skkiing",
  "Rafting",
  "Paradliding",
  "Visiiting the locals",
  "Swimming in hot springs",
  "Souvenir shopping",
  "Boat riding",
  "Relaxing on beach",
  "Excursions to museum",
  "City tour",
  "Visiting animal market",
  "Visiting local",
  "Bazaars",
  "Agro tourism",
  "Watching Kyrgyz movies",
];
