import { IFeedback } from "../components/FeedBack/Feedback";
export const FeedBackCards: IFeedback[] = [
    {
      id: 1,
      title: "Aman",
      country: "kg",
      stars: 5.5,
      desc: "We had a great time on 12 days best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage",
      link: "Tripadvisor",
      img: "/images/girl.svg",
    },
    {
      id: 1,
      title: "Aman",
      country: "kg",
      stars: 5,
      desc: "We had a great time on 12 days best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage...",
      link: "Tripadvisor",
      img: "/images/girl.svg",
    },
    {
      id: 1,
      title: "Aman",
      country: "kg",
      stars: 5,
      desc: "We had a great time on 12 days best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage...",
      link: "Tripadvisor",
      img: "/images/girl.svg",
    },
    {
      id: 1,
      title: "Aman",
      country: "kg",
      stars: 5,
      desc: "We had a great time on 12 days best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage",
      link: "Tripadvisor",
      img: "/images/girl.svg",
    },
    {
      id: 1,
      title: "Aman",
      country: "kg",
      stars: 5,
      desc: "We had a great time on 12 days best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage",
      link: "Tripadvisor",
      img: "/images/girl.svg",
    },
    {
      id: 1,
      title: "Aman",
      country: "kg",
      stars: 5,
      desc: "We had a great time on 12 days best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage best of Turkey. What made it amazing was the great people from down under, England, Spain and the USA. Samy, no words to describe your sage",
      link: "Tripadvisor",
      img: "/images/girl.svg",
    },
  ];
